In [ ]:
hello = "Hello, world!"
print(hello)

In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3,4])

In [ ]:
a

In [ ]:
a[2]

In [ ]:
import pandas as pd

In [ ]:
a[-1]

In [7]:
c=a.copy

In [8]:
c


<function ndarray.copy>

In [9]:
d=a.view()
d

array([1, 2, 3, 4])

In [10]:
a[2]=3.5

In [11]:
a
c

<function ndarray.copy>

In [12]:
a

array([1, 2, 3, 4])

In [13]:
c

<function ndarray.copy>

In [15]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b=a.reshape(4,3)
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [18]:
c=np.array([13,14,15])
d=np.concatenate((a,c))
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [21]:
np.array_split(d,3)

[array([1, 2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10]),
 array([11, 12, 13, 14, 15])]

In [23]:
np.where(d%2==0)

(array([ 1,  3,  5,  7,  9, 11, 13], dtype=int64),)

In [28]:
np.size(d)


15

In [31]:
np.random.rand(5)

array([0.73502251, 0.03633535, 0.11979141, 0.13590456, 0.86131364])